myfamilytree/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^treebuilder/', include('treebuilder.urls')),
    url(r'^admin/', admin.site.urls),
]

treebuilder/urls.py
from django.conf.urls import *
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

app_name = 'treebuilder'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<person_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^profile/$', views.index, name='index'),
    url(r'^browse/$', views.index, name='index'),
    url(r'^help/$', views.index, name='index'),
    url(r'^api/$', views.PersonList.as_view()),
    url(r'^profile/api/(?P<pk>[0-9]+)/$', views.PersonDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

treebuilder/models.py
from django.db import models
from datetime import date

# Create your models here.
class Person(models.Model):
	first_name = models.CharField(max_length=50)
	middle_name = models.CharField(max_length=50, null=True, blank=True)
	last_name = models.CharField(max_length=50)
	gender = models.CharField(max_length=1)
	date_of_birth = models.DateField()
	date_of_death = models.DateField(null=True, blank=True)
	father = models.ForeignKey('self', null=True, blank=True, related_name='%(class)s_father')
	mother = models.ForeignKey('self', null=True, blank=True, related_name='%(class)s_mother')

	def __str__(self):
		return "%s, %s" % (self.last_name, self.first_name)

	def full_name(self):
		return "%s %s" % (self.first_name, self.last_name)

	def is_deceased(self):
		return self.date_of_death is not None

	def age(self):
		if self.is_deceased():
			today = self.date_of_death
		else:
			today = date.today()
		years_difference = today.year - self.date_of_birth.year
		is_before_birthday = (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day)
		elapsed_years = years_difference - int(is_before_birthday)
		return elapsed_years

	def father_name(self):
		if self.father:
			return self.father.full_name()
		return None

	def mother_name(self):
		if self.mother:
			return self.mother.full_name()
		return None

	def parents(self):
		return [self.father, self.mother]

	def children(self, spouse=None):
		children = []
		for c in Person.objects.all():
			if spouse == None:
				if self in c.parents():
					children.append(c)
			else:
				if self in c.parents() and spouse in c.parents():
					children.append(c)
		return children

	def marriages(self):
		marriages = []
		for m in Marriage.objects.all():
			if self in m.spouses():
				marriages.append(m)
		return marriages

	def spouses(self):
		spouses = []
		marriages = self.marriages()
		for m in marriages:
			spouses.append(m.spouse(self))
		return spouses

class Marriage(models.Model):
	spouse1 = models.ForeignKey('Person', related_name='%(class)s_spouse1')
	spouse2 = models.ForeignKey('Person', related_name='%(class)s_spouse2')
	date_of_marriage = models.DateField(null=True, blank=True)
	date_of_divorce = models.DateField(null=True, blank=True)

	def __str__(self):
		return "%s / %s" % (self.spouse1, self.spouse2)

	def spouses(self):
		return [self.spouse1, self.spouse2]

	def spouse(self, person):
		if self.spouse1.id == person.id:
			return self.spouse2
		elif self.spouse2.id == person.id:
			return self.spouse1
		else:
			return None

treebuilder/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.shortcuts import render

#from rest_framework.decorator import permission_classes
#from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response
from rest_framework import status, generics
from .serializers import PersonSerializer

from .models import Person

# Create your views here.
def index(request):
	#return HttpResponse("Hello, world. You're at the treebuilder index.")
	latest_person_list = Person.objects.order_by('-date_of_birth')[:10]
	context = {
		'latest_person_list': latest_person_list,
	}
	return render(request, 'treebuilder/index.html', context)

def detail(request, person_id):
	#return HttpResponse("You're looking at person %s." % person_id)
	try:
		person = Person.objects.get(pk=person_id)
	except Person.DoesNotExist:
		raise Http404("Person does not exist")
	return render(request, 'treebuilder/detail.html', {'person':person, 'person_id':person_id})

class PersonList(generics.ListCreateAPIView):
	queryset = Person.objects.all()
	serializer_class = PersonSerializer

	def get(self, request, format=None):
		person = Person.objects.all().order_by('-date_of_birth')
		serializer = PersonSerializer(person, many=True)
		return Response(serializer.data)

	#@permission_classes((IsAdminUser, ))
	def post(self, request, format=None):
		user = request.user
		serializer = PersonSerializer(data=request.data, context={'user':user})
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data, status=status.HTTP_201_CREATED)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class PersonDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = Person.objects.all()
	serializer_class = PersonSerializer

treebuilder/templates/treebuilder/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>
      {% block title %}
      {% endblock %}
    </title>

    <!-- Bootstrap -->
  	{% load static %}
  	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/sitestyle.css' %}" />
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  
    {% block content %}
    {% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    {% load static %}
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>

treebuilder/templates/treebuilder/detail.html
{% extends 'treebuilder/base.html' %}

{% block title %}Person{% endblock %}

{% block content %}

    <h1>{{ person.full_name }}</h1>

	First Name: {{ person.first_name }}<br/>
	Middle Name: {{ person.middle_name }}<br/>
	Last Name: {{ person.last_name }}<br/>
	Gender: {{ person.gender }}<br/>
	Date of Birth: {{ person.date_of_birth }}<br/>

	{% if person.date_of_death %}
		Date of Death: {{ person.date_of_death }}<br/>
	{% endif %}

	Age: {{ person.age }}<br/>
	Father:
		{% if person.father %}
			<a href="{% url 'treebuilder:detail' person.father.id %}">{{person.father}}</a>
		{% else %}
			Unknown
		{% endif %}
		<br/>
	Mother:
		{% if person.mother %}
			<a href="{% url 'treebuilder:detail' person.mother.id %}">{{person.mother}}</a>
		{% else %}
			Unknown
		{% endif %}
		<br/>

	{% if person.marriages %}
	Marriages:<br/>
	{% for marriage in person.marriages %}
	    {% for spouse in marriage.spouses %}
	    	{% if spouse == person %}
	    	{% else %}
	    		Spouse: <a href="{% url 'treebuilder:detail' spouse.id %}">{{ spouse.full_name }}</a><br/>
	    	{% endif %}
	    {% endfor %}
	    {% if marriage.date_of_marriage %}
	    Date of marriage: {{ marriage.date_of_marriage }}<br/>
	    {% endif %}
		{% if marriage.date_of_divorce %}
	    Date of divorce: {{ marriage.date_of_divorce }}<br/>
	    {% endif %}
	{% endfor %}
	{% endif %}


	{% if person.children %}
	Children: 
	<ul>
	{% for child in person.children %}
	    <li><a href="{% url 'treebuilder:detail' child.id %}">{{ child.full_name }}</a></li>
	{% endfor %}
	</ul>
	{% endif %}

	<hr/>
	<a href="{% url 'treebuilder:index' %}">Return to Index</a>

{% endblock %}

treebuilder/templates/treebuilder/index.html
{% extends 'treebuilder/base.html' %}

{% block title %}List{% endblock %}

{% block content %}
    {% load render_bundle from webpack_loader %}

	<div id="container"></div>
	{% render_bundle 'main' %}

{% endblock %}